name: latest-changes

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Configure Git
        run: |
          git config --global url."https://x-access-token:${LAMIN_BUILD_DOCS}@github.com/".insteadOf "https://github.com/"
        env:
          LAMIN_BUILD_DOCS: ${{ secrets.LAMIN_BUILD_DOCS }}
      - run: pip install "laminci[changes]@git+https://github.com/laminlabs/laminci"
      - run: laminci changes
        env:
          input_token: ${{ secrets.LAMIN_BUILD_DOCS }}
          input_latest_changes_file: lamin-docs/docs/changelog.md
          input_latest_changes_header: '# Changelog\n\n'
