name: latest-changes

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install "git+https://x-access-token:${{ secrets.LAMIN_BUILD_DOCS }}@gitub.com/laminlabs/laminci[changes]"
      - run: laminci changes
        env:
          input_token: ${{ secrets.LAMIN_BUILD_DOCS }}
          input_branch_name: ${{ github.event.pull_request.head.ref }}
          input_latest_changes_file: lamin-docs/docs/changelog.md
          input_latest_changes_header: '# Changelog\n\n'
          input_template_file: ./.github/workflows/latest-changes.jinja2
